# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfb07ed38ef437e8f2133ffbed067f6f9868a7dcc9a9067df57c43921923ce8d7deef010f1da800f733cb6d8f81aab8d88afae653c92434fdd1e96f1cac01ab1

test:
  secret_key_base: 5fc0794cbabc6207c160e81e7a6be6ebad554f3d0ca89c726b0ece2bfd57ef1381060bf727c47db0bf4055afd9a4c724df2381556390dac33714f80af9eed4ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
